---
title: ICC Bot
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    theme: yeti
    source_code: https://github.com/tjmahr/iccbot
    md_extensions: "-tex_math_single_backslash"
runtime: shiny
bibliography: refs.bib
csl: apa.csl
---

```{r setup, include = FALSE}
library(tidyverse)
library(flexdashboard)
library(shiny)
library(irr)
library(printy)

# Default dataset from Shrout and Fleiss.
d <- tibble::tibble(
  Judge1 = c(9, 6, 8, 7, 10, 6),
  Judge2 = c(2, 1, 4, 1,  5, 2),
  Judge3 = c(5, 3, 6, 2,  6, 4),
  Judge4 = c(8, 2, 8, 6,  9, 7)
)

getData <- function() {
  if (is.null(input$file1)) {
    d
  } else {
    read.csv(input$file1$datapath)
  }
}

runICC <- function() {
  req(input$use_twoway_model)
  req(input$single_or_average)
  req(input$agreement_or_consistency)
  
  model <- ifelse(
    input$use_twoway_model == "yes (two-way model)", 
    "twoway", 
    "oneway"
  )
  unit  <- ifelse(
    input$single_or_average == "single rating", 
    "single", 
    "average"
  )
  type <- ifelse(
    input$agreement_or_consistency == "absolute agreement", 
    "agreement", 
    "consistency"
  )
  
  add_formatted_results_to_icc(
    icc(
      getData(),
      model = model,
      unit = unit,
      type = type
    )
  )
}

add_formatted_results_to_icc <- function(icc, icc_digits = 3) {
  icc$lbound_p <- icc$lbound %>% 
    printy::fmt_fix_digits(icc_digits) %>% 
    printy::fmt_leading_zero()
  
  icc$ubound_p <- icc$ubound %>% 
    printy::fmt_fix_digits(icc_digits) %>% 
    printy::fmt_leading_zero()
  
  icc$value <- icc$value %>% 
    printy::fmt_fix_digits(icc_digits) %>% 
    printy::fmt_leading_zero()
  
  icc$model_p <- ifelse(
    icc$model == "twoway", 
    "two-way", 
    "one-way"
  )
  
  icc$unit_p <- ifelse(
    icc$unit == "single", 
    "a single-score", 
    "an average-score"
  )
  
  icc$unit_p2 <- ifelse(
    icc$unit == "single", 
    "raters", 
    "average ratings"
  )
  
  icc$type_p <- ifelse(
    icc$type == "consistency", 
    "consistency-based", 
    "absolute agreement"
  )
  
  icc$raters_p <- ifelse(
    icc$model == "twoway", 
    sprintf("%s raters", icc$raters), 
    sprintf(
      "%s different raters (%s unique raters)", 
      icc$raters, 
      icc$raters *  icc$subjects
    )
  )
  
  icc
}

i <- reactive(list(
  subjects = runICC()[["subjects"]],
  n_trials = runICC()[["raters"]],
  unit_p = runICC()[["unit_p"]],
  unit_p2 = runICC()[["unit_p2"]],
  type_p = runICC()[["type_p"]],
  model_p = runICC()[["model_p"]],
  icc.name = runICC()[["icc.name"]],
  value = runICC()[["value"]],
  lbound_p = runICC()[["lbound_p"]],
  ubound_p = runICC()[["ubound_p"]],
  raters_p = runICC()[["raters_p"]]
))
```



Column {.sidebar}
======================================================================

Upload a csv file of scores with one column per rater and no other columns.

```{r, echo = FALSE}
fileInput(
  "file1", 
  "Choose CSV File", 
  accept = c(
    "text/csv",
    "text/comma-separated-values,text/plain",
    ".csv")
)

selectInput(
  "use_twoway_model",
  label = "Do raters evaluate more than one participant?", 
  choices = c("yes (two-way model)", "no (one-way model)"), 
  multiple = FALSE 
)

selectInput(
  "single_or_average",
  label = "Do you want the reliability for a single rating or the reliability for the average rating?", 
  choices = c("single rating", "average rating"),
  multiple = FALSE 
)

renderUI({
  req(input$use_twoway_model)
  
  choices <- if (input$use_twoway_model == "no (one-way model)") {
    c("consistency")
  } else {
    c("absolute agreement", "consistency")
  }
  
  label <- if (input$use_twoway_model == "no (one-way model)") {
    HTML("<s>Do you want to estimate agreement of raters or consistency of raters?</s> Agreement is not available for one-way models.")
    
  } else {
    "Do you want to estimate agreement of raters or consistency of raters?"
  }
  
  selectInput(
    "agreement_or_consistency",
    label = label, 
    choices = choices,
    multiple = FALSE
  )
})
```

***

<small>
Developed by TJ Mahr for
<a href="https://kidspeech.wisc.edu/" target="_blank">The WISC Lab</a>.
</small>




<span class="fa fa-robot" style="margin-right: 7px;"></span>Run ICC Bot
======================================================================


Column {data-width=400}
-----------------------------------------------------------------------

### ICC Bot says

We calculated the interrater reliability of [`instrument name`] with the
intraclass correlation coefficient (ICC) estimated using the irr R package
[vers. `r packageVersion("irr")`; @R-irr]. Each of the
`r renderText(i()[["subjects"]])` participants were scored by
`r renderText(i()[["raters_p"]])`.

We used `r renderText(i()[["unit_p"]])`, `r renderText(i()[["type_p"]])`,
`r renderText(i()[["model_p"]])` random effects model, and we found
[`interpret the correlation`] agreement among `r renderText(i()[["unit_p2"]])`, `r renderText(i()[["icc.name"]])` =
`r renderText(i()[["value"]])`, 95% CI =
[`r renderText(i()[["lbound_p"]])`,
`r renderText(i()[["ubound_p"]])`].

***

<div id="refs"></div>


Column {data-width=450}
-----------------------------------------------------------------------

### ICC printout

```{r}
renderPrint(runICC())
```

### First six rows of data

```{r}
renderPrint(head(getData()))
```




<span class="fa fa-book" style="margin-right: 7px;"></span>Bot Settings and ICC Interpretation 
======================================================================


```{r, child="icc-notes.md"}
```
